import { NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import prisma from "@/lib/prisma";

export type FaqItem = {
  id: string;
  category: string;
  question: string;
  answer: string;
};

const FAQS: FaqItem[] = [
  // Skin Analysis
  {
    id: "a1",
    category: "Skin Analysis",
    question: "How does the skin analysis work?",
    answer:
      "DeepSkyn uses AI-powered computer vision to analyze your skin from a facial photo. The system detects visible conditions (acne, dark spots, pores, wrinkles, etc.), evaluates your skin type, and generates a personalized score and routine based on clinical dermatology guidelines.",
  },
  {
    id: "a2",
    category: "Skin Analysis",
    question: "How often should I do the analysis?",
    answer:
      "We recommend doing a full analysis every 4–6 weeks. Your skin changes gradually, and this interval gives enough time to see the effect of your routine. You can track progress over time in the Analyzes section.",
  },
  {
    id: "a3",
    category: "Skin Analysis",
    question: "What does my skin score mean?",
    answer:
      "Your skin health score (0–100) reflects the overall condition of your skin across 6 dimensions: hydration, barrier function, clarity, calmness, protection, and lifestyle. A score above 70 is considered healthy. Lower scores indicate areas to improve.",
  },
  {
    id: "a4",
    category: "Skin Analysis",
    question: "Why is my score different each time?",
    answer:
      "Your score naturally varies with lighting, camera quality, skin hydration, sleep, and hormonal cycles. For accurate comparisons, always take photos in natural daylight, clean face, no makeup, at a consistent time of day.",
  },
  {
    id: "a5",
    category: "Skin Analysis",
    question: "What photo should I use for the analysis?",
    answer:
      "Use a clear frontal photo of your face in natural daylight. Ensure your full face is visible, no heavy shadows, no makeup, and the image is in focus. The AI requires a human face — other images will be rejected.",
  },
  // Routines
  {
    id: "r1",
    category: "Routines",
    question: "How are my routines generated?",
    answer:
      "Your AM/PM routine is generated by our AI based on your skin analysis results, questionnaire answers, and skin type. Each recommended step includes a specific active ingredient with its mechanism and concentration.",
  },
  {
    id: "r2",
    category: "Routines",
    question: "What is an AM/PM routine?",
    answer:
      "AM (morning) routine focuses on protection and hydration: cleanser, serum, moisturizer, SPF. PM (evening) routine focuses on repair and treatment: double cleanse, treatment actives (retinol, AHA/BHA), and barrier repair cream.",
  },
  {
    id: "r3",
    category: "Routines",
    question: "Can I customize my routine?",
    answer:
      "Yes. In the Routines section you can adjust steps, add or remove products, and mark steps as completed. Your routine evolves with each new analysis as your skin improves.",
  },
  {
    id: "r4",
    category: "Routines",
    question: "Why is SPF always in my morning routine?",
    answer:
      "SPF is the single most effective anti-aging and skin protection step. UV exposure degrades collagen, worsens hyperpigmentation, and counteracts all active treatments. SPF 30+ every morning is non-negotiable regardless of your skin type.",
  },
  // Products
  {
    id: "p1",
    category: "Products",
    question: "How are product recommendations made?",
    answer:
      "Product recommendations are based on your skin conditions, detected actives that target them, and compatibility with your skin type. Concentrations and formulations are matched to your sensitivity level.",
  },
  {
    id: "p2",
    category: "Products",
    question: "Where can I find the recommended products?",
    answer:
      "The Products section lists all recommended products with their key ingredients. You can search by ingredient, skin type, or condition. Products are curated from trusted skincare brands with verified formulations.",
  },
  {
    id: "p3",
    category: "Products",
    question: "Can I use products not recommended by DeepSkyn?",
    answer:
      "Yes, but check ingredient compatibility. Avoid combining: retinol + AHA/BHA in same routine, vitamin C + niacinamide (can cause flushing in high concentrations), and benzoyl peroxide + retinol.",
  },
  // Account
  {
    id: "ac1",
    category: "Account",
    question: "How do I update my profile information?",
    answer:
      "Go to Profile in the sidebar. You can update your name, profile photo, and personal details. Changes are saved automatically.",
  },
  {
    id: "ac2",
    category: "Account",
    question: "How do I change my password?",
    answer:
      "Go to Security in the sidebar. Enter your current password and your new password. If you signed in with Google, password change is managed through your Google account.",
  },
  {
    id: "ac3",
    category: "Account",
    question: "How do I delete my account?",
    answer:
      "Account deletion can be requested in Settings. All your data (analyses, routines, messages) will be permanently deleted. This action cannot be undone.",
  },
  // Billing
  {
    id: "b1",
    category: "Billing",
    question: "What is included in the free plan?",
    answer:
      "The free plan includes 1 skin analysis, access to basic routines, and limited product recommendations. Premium unlocks unlimited analyses, detailed reports, full product catalog, and priority support.",
  },
  {
    id: "b2",
    category: "Billing",
    question: "How do I upgrade to Premium?",
    answer:
      "Go to Billing in the sidebar. Choose your plan (monthly or annual) and complete the secure payment via Stripe. Your premium features are activated immediately after payment.",
  },
  {
    id: "b3",
    category: "Billing",
    question: "How do I cancel my subscription?",
    answer:
      "Go to Billing → Manage Subscription. You can cancel at any time. You keep access to premium features until the end of your billing period. No partial refunds are issued.",
  },
  {
    id: "b4",
    category: "Billing",
    question: "Is my payment information secure?",
    answer:
      "Yes. All payments are processed by Stripe, a PCI-DSS Level 1 certified payment provider. DeepSkyn never stores your card details.",
  },
  // Technical
  {
    id: "t1",
    category: "Technical",
    question: "Why isn't the camera working for the analysis?",
    answer:
      "Make sure you have granted camera permissions to your browser. On Chrome: click the lock icon in the address bar → Camera → Allow. On Safari: Settings → Safari → Camera → Allow.",
  },
  {
    id: "t2",
    category: "Technical",
    question: "The analysis is taking too long. What should I do?",
    answer:
      "Analysis usually completes in 10–30 seconds. If it takes longer, check your internet connection and try refreshing the page. If the issue persists, submit a bug report via Complaints & Feedback.",
  },
  {
    id: "t3",
    category: "Technical",
    question: "How do I report a bug?",
    answer:
      "Go to Complaints & Feedback in the sidebar. Select the Bug category and describe the issue in detail (what happened, what you expected, steps to reproduce). Screenshots can be attached as evidence.",
  },
];

export async function GET() {
  const session = await getServerSession(authOptions);
  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  return NextResponse.json({ faqs: FAQS });
}

export async function POST(request: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await request.json() as { question: string };
  const question = (body.question ?? "").trim();
  if (!question || question.length < 10) {
    return NextResponse.json({ error: "Question too short" }, { status: 400 });
  }

  const userId = Number((session.user as any).id);
  const complaint = await prisma.complaint.create({
    data: {
      user_id: userId,
      category: "OTHER",
      content: `[Help Center Question]\n\n${question}`,
      status: "PENDING",
    },
  });

  return NextResponse.json({ success: true, complaintId: complaint.id }, { status: 201 });
}
