import type { Metadata } from "next";
import { Figtree, Inter, Geist_Mono } from "next/font/google";
import "./css/globals.css"
import "./css/satoshi.css";
import "./css/lenis.css"
import { NavigationProvider } from "./components/NavigationProvider";
import SmoothScrollProvider from "./components/SmoothScrollProvider";
import AuthProvider from "./components/AuthProvider";
import { ToastProvider } from "./components/ToastProvider";
import { ReduxProvider } from "@/store/Provider";
import { ColorBlindFilterDefs } from "./components/ColorBlindFilterDefs";
import IntlProvider from "./components/IntlProvider";
import { getLocale, getMessages } from "next-intl/server";

const figtree = Figtree({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "DeepSkyn",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png',
    apple: '/apple-icon.png',
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const dir = locale === 'ar' ? 'rtl' : 'ltr';
  
  return (
    <html lang={locale} dir={dir} suppressHydrationWarning>
      <body
        className={`${figtree.variable} ${inter.variable} ${geistMono.variable} font-sans antialiased`}
        suppressHydrationWarning
      >
        <IntlProvider locale={locale} messages={messages}>
          <ReduxProvider>
            <ColorBlindFilterDefs />
            <AuthProvider>
              <SmoothScrollProvider>
                <NavigationProvider>
                  {children}
                </NavigationProvider>
              </SmoothScrollProvider>
            </AuthProvider>
            <ToastProvider />
          </ReduxProvider>
        </IntlProvider>
      </body>
    </html>
  );
}
