"use client";

import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useSession } from "next-auth/react";
import {
    Sun,
    Moon,
    Calendar,
    CheckCircle2,
    Circle,
    AlertTriangle,
    Flame,
    Clock,
    Play,
    RotateCcw,
    ArrowRight,
    Droplets,
    Plus,
    Trash2,
    ChevronRight,
} from "lucide-react";

import { UserLayout } from "@/app/ui/UserLayout";
import { toast } from "sonner";
import { RoutineItemScraper } from "@/app/components/user/RoutineItemScraper";
import { AudioToggleButton } from "@/app/components/user/AudioToggleButton";
import { useAppDispatch, useAppSelector } from "@/store/hooks";
import { deleteRoutine, fetchUserRoutines, markStepCompleted, toggleStepCompletedLocally } from "@/store/slices/routineSlice";
import { AddRoutineModal } from "@/app/components/user/AddRoutineModal";
import { DeleteRoutineModal } from "@/app/components/user/DeleteRoutineModal";
import { useTranslations } from "next-intl";

// --- Types ---
type RoutineType = "morning" | "night" | "weekly";

type ConsistencyResponse = {
    type: RoutineType;
    percentage: number;
    streak: number;
    days: Array<{ day: string; completed: boolean }>;
};

type ParsedRoutineMeta = {
    isAutoGenerated: boolean;
    idempotencyKey?: string;
    source?: string;
    skinType?: string;
    score?: string;
    durationWeeks?: string;
    warnings?: string;
    motivationText?: string;
};

const parseRoutineMeta = (envie?: string): ParsedRoutineMeta => {
    const raw = String(envie || "").trim();
    if (!raw.startsWith("AUTO_ROUTINE:")) {
        return {
            isAutoGenerated: false,
            motivationText: raw,
        };
    }

    const parts = raw.split(" | ").map((p) => p.trim()).filter(Boolean);
    const meta: ParsedRoutineMeta = {
        isAutoGenerated: true,
    };

    for (let i = 0; i < parts.length; i += 1) {
        const token = parts[i];
        if (i === 0 && token.startsWith("AUTO_ROUTINE:")) {
            meta.idempotencyKey = token.replace("AUTO_ROUTINE:", "").trim();
            continue;
        }

        if (token.startsWith("source=")) {
            meta.source = token.replace("source=", "").trim();
            continue;
        }

        if (token.startsWith("skinType=")) {
            meta.skinType = token.replace("skinType=", "").trim();
            continue;
        }

        if (token.startsWith("score=")) {
            meta.score = token.replace("score=", "").trim();
            continue;
        }

        if (token.startsWith("durationWeeks=")) {
            meta.durationWeeks = token.replace("durationWeeks=", "").trim();
            continue;
        }

        if (token.startsWith("warnings=")) {
            const warningHead = token.replace("warnings=", "").trim();
            const warningTail = parts.slice(i + 1).join(" | ").trim();
            meta.warnings = warningTail ? `${warningHead} | ${warningTail}` : warningHead;
            break;
        }
    }

    meta.motivationText = "Routine generated automatically from your latest quiz analysis.";
    return meta;
};

const cleanAutoGoalLabel = (objectif?: string, isAutoGenerated?: boolean) => {
    const raw = String(objectif || "").trim();
    if (!raw) return "Routine";
    if (!isAutoGenerated) return raw;
    return raw
        .replace(/\s-\sMorning$/i, "")
        .replace(/\s-\sEvening$/i, "")
        .replace(/\s-\sWeekly Plan$/i, "")
        .trim();
};

// --- Components ---

const ProgressBar = ({ current, total, type }: { current: number; total: number; type: string }) => {
    const t = useTranslations("userRoutines");
    const percentage = total > 0 ? (current / total) * 100 : 0;
    const localizedType = ["morning", "night", "weekly"].includes(type)
        ? t(`tabs.${type}`)
        : type;
    return (
        <div className="relative flex items-center justify-center p-6 bg-card dark:bg-card/40 border border-border/50 rounded-3xl shadow-xl shadow-primary/5">
            <div className="relative w-24 h-24">
                <svg className="w-full h-full -rotate-90">
                    <circle
                        cx="48"
                        cy="48"
                        r="40"
                        stroke="currentColor"
                        strokeWidth="8"
                        fill="transparent"
                        className="text-muted/20"
                    />
                    <motion.circle
                        cx="48"
                        cy="48"
                        r="40"
                        stroke="currentColor"
                        strokeWidth="8"
                        fill="transparent"
                        strokeDasharray="251.2"
                        initial={{ strokeDashoffset: 251.2 }}
                        animate={{ strokeDashoffset: 251.2 - (251.2 * percentage) / 100 }}
                        transition={{ duration: 1, ease: "easeOut" }}
                        strokeLinecap="round"
                        className="text-primary"
                    />
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                    <span className="text-xl font-black text-foreground">{current}/{total}</span>
                </div>
            </div>
            <div className="ml-6 flex-1">
                <h4 className="text-sm font-black text-muted-foreground uppercase tracking-widest mb-1">
                    {t("progress.routineType", { type: localizedType })}
                </h4>
                <p className="text-lg font-bold text-foreground leading-tight">
                    {percentage === 100 ? t("progress.sparkle") : percentage > 50 ? t("progress.halfway") : t("progress.keepGoing")}
                </p>
            </div>
        </div>
    );
};

const SequentialWarningModal = ({ isOpen, onClose, message }: { isOpen: boolean; onClose: () => void; message: string }) => {
    const t = useTranslations();
    return (
        <AnimatePresence>
            {isOpen && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm">
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9, y: 20 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.9, y: 20 }}
                        className="w-full max-w-md bg-card border border-border rounded-[2rem] p-8 shadow-2xl relative overflow-hidden"
                    >
                        <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 rounded-full -mr-16 -mt-16 blur-3xl" />
                        <div className="relative flex flex-col items-center text-center">
                            <div className="w-20 h-20 bg-primary/10 rounded-3xl flex items-center justify-center mb-6">
                                <AlertTriangle className="w-10 h-10 text-primary" />
                            </div>
                            <h3 className="text-2xl font-black text-foreground mb-3 leading-tight">
                                {t("userRoutines.toasts.validationRequired")}
                            </h3>
                            <p className="text-muted-foreground text-lg leading-relaxed mb-8">
                                {message}
                            </p>
                            <button
                                onClick={onClose}
                                className="w-full py-4 bg-primary text-primary-foreground font-black rounded-2xl hover:bg-primary/90 transition-all shadow-lg shadow-primary/20 active:scale-95"
                            >
                                {t("userRoutines.toasts.gotIt")}
                            </button>
                        </div>
                    </motion.div>
                </div>
            )}
        </AnimatePresence>
    );
};

export default function RoutinePage() {
    const t = useTranslations();
    const { data: session } = useSession();
    const dispatch = useAppDispatch();
    const { routines, loading } = useAppSelector((state) => state.routine);
    type RoutineRecord = (typeof routines)[number];
    const [activeTab, setActiveTab] = useState<RoutineType>("morning");
    const [userName, setUserName] = useState("");
    const [userId, setUserId] = useState<number | null>(null);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [routineToEdit, setRoutineToEdit] = useState<RoutineRecord | null>(null);
    const [isDeleteModalOpen, setIsDeleteModalOpen] = useState(false);
    const [routineToDelete, setRoutineToDelete] = useState<RoutineRecord | null>(null);
    const [deleteLoading, setDeleteLoading] = useState(false);
    const [consistency, setConsistency] = useState<ConsistencyResponse | null>(null);
    const [consistencyLoading, setConsistencyLoading] = useState(false);
    const [isPremiumUser, setIsPremiumUser] = useState(false);
    const [isScrapingEnabled, setIsScrapingEnabled] = useState(true);
    const [speakingIndex, setSpeakingIndex] = useState<string | null>(null);
    const [autoSpeech, setAutoSpeech] = useState(false);
    const [isWarningModalOpen, setIsWarningModalOpen] = useState(false);
    const [warningModalMessage, setWarningModalMessage] = useState("");

    // Fetch user and routines
    useEffect(() => {
        const fetchUserData = async () => {
            if (session?.user?.email) {
                try {
                    const response = await fetch('/api/user/profile');
                    if (response.ok) {
                        const userData = await response.json();
                        setUserName(userData.nom || "User");
                        setUserId(userData.id);

                        const now = Date.now();
                        const hasActiveSubscription = Array.isArray(userData.subscriptions)
                            && userData.subscriptions.some((sub: { date_fin?: string }) => {
                                if (!sub?.date_fin) return false;
                                const endAt = new Date(sub.date_fin).getTime();
                                return Number.isFinite(endAt) && endAt >= now;
                            });

                        setIsPremiumUser(userData.role === "PREMIUM_USER" || hasActiveSubscription);

                        // Fetch routines
                        if (userData.id) {
                            dispatch(fetchUserRoutines(userData.id));
                        }
                    }
                } catch (error) {
                    console.error('Error fetching user data:', error);
                }
            }
        };
        fetchUserData();
    }, [session, dispatch]);

    // Fetch consistency for current tab
    useEffect(() => {
        let cancelled = false;
        const run = async () => {
            try {
                setConsistencyLoading(true);
                const res = await fetch(`/api/user/routines/consistency?type=${activeTab}`);
                if (!res.ok) throw new Error("Failed to load consistency");
                const data = (await res.json()) as ConsistencyResponse;
                if (!cancelled) setConsistency(data);
            } catch {
                if (!cancelled) setConsistency(null);
            } finally {
                if (!cancelled) setConsistencyLoading(false);
            }
        };
        run();
        return () => {
            cancelled = true;
        };
    }, [activeTab]);

    // Filter routines by active tab
    const currentRoutines = routines.filter(r => r.type === activeTab);
    const currentSteps = currentRoutines.flatMap((r) => r.steps || []);
    const completedCount = currentSteps.filter(s => s.completed).length;

    const toggleStep = async (routineId: number, stepId: number) => {
        // Find routine directly from state to ensure we have latest data
        const routine = routines.find((r) => r.id === routineId);
        if (!routine || !routine.steps) return;

        const sortedSteps = [...routine.steps].sort((a, b) => a.ordre - b.ordre);
        const stepIndex = sortedSteps.findIndex((s) => s.id === stepId);
        const step = sortedSteps[stepIndex];
        
        if (!step) return;

        const isMarkingCompleted = !step.completed;

        // Constraint: only apply when trying to mark a step as completed
        if (isMarkingCompleted && stepIndex > 0) {
            const previousStep = sortedSteps[stepIndex - 1];
            if (!previousStep.completed) {
                setWarningModalMessage(t("userRoutines.toasts.previousStepRequired"));
                setIsWarningModalOpen(true);
                return;
            }
        }

        dispatch(toggleStepCompletedLocally({ routineId, stepId }));

        try {
            await dispatch(markStepCompleted({
                routineId,
                stepId,
                completed: isMarkingCompleted
            })).unwrap();

            if (isMarkingCompleted) {
                const stepData = routine?.steps?.find((s) => s.id === stepId);
                toast.success(t("userRoutines.toasts.stepCompleted", { step: stepData?.action || t("userRoutines.toasts.step") }), {
                    description: t("userRoutines.toasts.stepCompletedDescription"),
                });
            }
        } catch {
            dispatch(toggleStepCompletedLocally({ routineId, stepId }));
            toast.error(t("userRoutines.toasts.updateFailed"));
        }
    };

    const handleNewRoutine = () => {
        setRoutineToEdit(null);
        setIsScrapingEnabled(false);
        setIsModalOpen(true);
    };

    const handleEditRoutine = (routine: RoutineRecord) => {
        setRoutineToEdit(routine);
        setIsScrapingEnabled(false);
        setIsModalOpen(true);
    };

    const handleCloseRoutineModal = () => {
        setIsModalOpen(false);

        // Enforce a strict sequence: save routine + steps first, then start scraping.
        window.setTimeout(() => {
            setIsScrapingEnabled(true);
        }, 800);
    };

    const handleDeleteRoutine = (routine: RoutineRecord) => {
        setRoutineToDelete(routine);
        setIsDeleteModalOpen(true);
    };

    const confirmDeleteRoutine = async () => {
        if (!routineToDelete) return;
        setDeleteLoading(true);
        try {
            await dispatch(deleteRoutine(routineToDelete.id)).unwrap();
            toast.success(t("userRoutines.toasts.routineDeleted"));
            setIsDeleteModalOpen(false);
        } catch {
            toast.error(t("userRoutines.toasts.deleteFailed"));
        } finally {
            setDeleteLoading(false);
        }
    };

    const stopSpeaking = () => {
        if (typeof window !== 'undefined') {
            window.speechSynthesis.cancel();
            setSpeakingIndex(null);
        }
    };

    const speakText = (text: string, id: string) => {
        if (typeof window === 'undefined') return;

        if (speakingIndex === id) {
            stopSpeaking();
            return;
        }

        stopSpeaking();

        const utterance = new SpeechSynthesisUtterance(text);

        // Dynamic language detection
        if (/[\u0600-\u06FF]/.test(text)) {
            utterance.lang = 'ar-SA';
        } else if (/[éèàùâêîôûëïü]/.test(text.toLowerCase())) {
            utterance.lang = 'fr-FR';
        } else {
            utterance.lang = 'en-US';
        }

        utterance.rate = 1.1; // Slightly faster for a modern feel
        utterance.pitch = 1.0;

        utterance.onend = () => {
            setSpeakingIndex(null);
        };

        utterance.onerror = () => {
            setSpeakingIndex(null);
        };

        setSpeakingIndex(id);
        window.speechSynthesis.speak(utterance);
    };

    // Auto-read routine when tab changes or autoSpeech toggled
    useEffect(() => {
        if (autoSpeech && currentRoutines.length > 0) {
            // Let's build a clean descriptive text
            let fullText = t("userRoutines.speech.summary", { userName, tab: activeTab, count: currentSteps.length });
            const percentage = currentSteps.length > 0 ? Math.round((completedCount / currentSteps.length) * 100) : 0;
            fullText += t("userRoutines.speech.completion", { percentage });

            if (consistency) {
                fullText += t("userRoutines.speech.streak", { streak: consistency.streak });
            }

            fullText += t("userRoutines.speech.guidelines");
            currentSteps.forEach((step, idx) => {
                fullText += t("userRoutines.speech.step", { index: idx + 1, action: step.action });
            });

            const id = `routine-full-${activeTab}-${currentSteps.length}-${completedCount}-${consistency?.streak || 0}`;
            if (speakingIndex !== id) {
                speakText(fullText, id);
            }
        }
        // Intentional limited dependencies to avoid restarting voice synthesis too frequently.
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [activeTab, autoSpeech, currentRoutines.length, completedCount, consistency?.streak]);

    useEffect(() => {
        return () => {
            if (typeof window !== 'undefined') {
                window.speechSynthesis.cancel();
            }
        };
    }, []);

    return (
        <UserLayout userName={userName} userPhoto="/avatar.png">
            <div className="user-routines-page min-h-full py-6 px-4 md:px-8 max-w-[1200px] mx-auto relative space-y-6">

                {/* Breadcrumb */}
                <nav className="flex items-center gap-2 text-sm text-muted-foreground/60">
                    <span>{t("userRoutines.breadcrumb.user")}</span>
                    <ChevronRight size={14} />
                    <span className="text-foreground font-medium">{t("userRoutines.breadcrumb.routines")}</span>
                </nav>


                {/* Header Section */}
                <header className="mb-12 flex flex-col md:flex-row md:items-end justify-between gap-8">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="space-y-3"
                    >
                        <div className="flex items-center gap-4">
                            <h1 className="text-4xl md:text-5xl font-black tracking-tight text-foreground">
                                Hello, {userName}
                            </h1>
                            <AudioToggleButton
                                enabled={autoSpeech}
                                onToggle={() => {
                                    if (autoSpeech) stopSpeaking();
                                    setAutoSpeech(!autoSpeech);
                                }}
                            />
                        </div>
                        <div className="flex flex-wrap gap-2 pt-1">
                            {["Dry", "Sensitive", "Eco-Conscious"].map(tag => (
                                <span key={tag} className="px-3 py-1 bg-primary/5 text-primary border border-primary/10 rounded-full text-[10px] font-black uppercase tracking-wider">
                                    {tag}
                                </span>
                            ))}
                        </div>
                    </motion.div>

                    <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="w-full md:w-auto min-w-[300px]"
                    >
                        <ProgressBar current={completedCount} total={currentSteps.length} type={activeTab} />
                    </motion.div>
                </header>

                {/* Tab Switcher */}
                <div className="flex flex-wrap items-center gap-4 mb-10">
                    <div className="flex p-1.5 bg-muted/30 backdrop-blur-md rounded-[24px] border border-border/50">
                        {[
                            { id: "morning", label: t("userRoutines.tabs.morning"), icon: Sun },
                            { id: "night", label: t("userRoutines.tabs.night"), icon: Moon },
                            { id: "weekly", label: t("userRoutines.tabs.weekly"), icon: Calendar },
                        ].map((tab) => (
                            <button
                                key={tab.id}
                                onClick={() => setActiveTab(tab.id as RoutineType)}
                                className={`flex items-center gap-2.5 px-6 py-3 rounded-full text-xs font-black uppercase tracking-widest transition-all duration-300 ${activeTab === tab.id
                                    ? "bg-card text-foreground shadow-lg shadow-black/5 border border-border/10"
                                    : "text-muted-foreground hover:text-foreground"
                                    }`}
                            >
                                <tab.icon className={`w-4 h-4 ${activeTab === tab.id ? "text-primary" : ""}`} />
                                {tab.label}
                            </button>
                        ))}
                    </div>

                    <button
                        onClick={handleNewRoutine}
                        className="flex items-center gap-2 px-6 py-3 bg-primary text-primary-foreground rounded-full text-xs font-black uppercase tracking-widest hover:scale-105 active:scale-95 transition-all shadow-lg shadow-primary/20"
                    >
                        <Plus className="w-4 h-4" />
                        {t("userRoutines.actions.newRoutine")}
                    </button>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-start">
                    <div className="lg:col-span-8 space-y-6">
                        <h3 className="text-xl font-black text-foreground mb-6 flex items-center gap-3 uppercase tracking-tighter">
                            {t("userRoutines.labels.routineType", { type: activeTab })}
                            <span className="h-px flex-1 bg-border/50" />
                        </h3>

                        {loading ? (
                            <div className="flex items-center justify-center py-20">
                                <div className="animate-spin rounded-full h-12 w-12 border-4 border-primary border-t-transparent"></div>
                            </div>
                        ) : currentRoutines.length === 0 ? (
                            <div className="text-center py-20">
                                <div className="inline-flex p-6 bg-muted/30 rounded-full mb-6">
                                    <Calendar className="w-12 h-12 text-muted-foreground" />
                                </div>
                                <h3 className="text-xl font-black text-foreground mb-2">
                                    {t("userRoutines.states.noRoutines", { type: activeTab })}
                                </h3>
                                <p className="text-muted-foreground mb-8">
                                    {t("userRoutines.states.noRoutinesDescription")}
                                </p>
                                <button
                                    onClick={handleNewRoutine}
                                    className="inline-flex items-center gap-2 px-8 py-4 bg-primary text-primary-foreground rounded-full font-black uppercase tracking-widest hover:scale-105 transition-all shadow-lg shadow-primary/20"
                                >
                                    <Plus className="w-5 h-5" />
                                    {t("userRoutines.actions.createRoutine")}
                                </button>
                            </div>
                        ) : (
                            <div className="space-y-4">
                                {currentRoutines.map((routine) => {
                                    const routineMeta = parseRoutineMeta(routine.envie);
                                    const cleanGoal = cleanAutoGoalLabel(routine.objectif, routineMeta.isAutoGenerated);

                                    return (
                                        <div key={routine.id} className="space-y-4">
                                            <div className="flex items-center justify-between gap-4">
                                                <div className="min-w-0">
                                                    <p className="text-xs font-black uppercase tracking-widest text-muted-foreground/60">
                                                        {routineMeta.isAutoGenerated ? t("userRoutines.labels.aiRoutine") : t("userRoutines.labels.routine")}
                                                    </p>
                                                    <h4 className="text-lg font-black text-foreground truncate">
                                                        {cleanGoal || routine.envie || t("userRoutines.labels.routine")}
                                                    </h4>
                                                </div>
                                                <div className="flex items-center gap-2">
                                                    <button
                                                        type="button"
                                                        onClick={() => handleEditRoutine(routine)}
                                                        className="flex items-center gap-2 px-4 py-2 rounded-2xl bg-primary/10 border border-primary/20 text-xs font-black uppercase tracking-widest text-primary hover:bg-primary/20 transition-colors"
                                                    >
                                                        {t("userRoutines.actions.edit")}
                                                    </button>
                                                    <button
                                                        type="button"
                                                        onClick={() => handleDeleteRoutine(routine)}
                                                        className="flex items-center gap-2 px-4 py-2 rounded-2xl bg-muted/30 border border-border/50 text-xs font-black uppercase tracking-widest text-muted-foreground hover:text-foreground hover:bg-muted/50 transition-colors"
                                                    >
                                                        <Trash2 className="w-4 h-4" />
                                                        {t("userRoutines.actions.delete")}
                                                    </button>
                                                </div>
                                            </div>

                                            {(routineMeta.skinType || routineMeta.score || routineMeta.durationWeeks) && (
                                                <div className="flex flex-wrap gap-2">
                                                    {routineMeta.skinType && (
                                                        <span className="px-3 py-1 rounded-full bg-primary/10 text-primary text-[10px] font-black uppercase tracking-widest border border-primary/20">
                                                            {t("userRoutines.meta.skin")}: {routineMeta.skinType}
                                                        </span>
                                                    )}
                                                    {routineMeta.score && (
                                                        <span className="px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 text-[10px] font-black uppercase tracking-widest border border-emerald-500/20">
                                                            {t("userRoutines.meta.score")}: {routineMeta.score}/100
                                                        </span>
                                                    )}
                                                    {routineMeta.durationWeeks && (
                                                        <span className="px-3 py-1 rounded-full bg-sky-500/10 text-sky-700 dark:text-sky-300 text-[10px] font-black uppercase tracking-widest border border-sky-500/20">
                                                            {t("userRoutines.meta.duration")}: {routineMeta.durationWeeks} {t("userRoutines.meta.weeks")}
                                                        </span>
                                                    )}
                                                </div>
                                            )}

                                            {(routine.objectif || routine.envie) && (
                                                <div className="bg-primary/5 border border-primary/10 rounded-3xl p-6 mb-6">
                                                    {routineMeta.motivationText && (
                                                        <p className="text-sm font-bold text-foreground mb-2">
                                                            <span className="text-primary">{t("userRoutines.labels.motivation")}</span> {routineMeta.motivationText}
                                                        </p>
                                                    )}
                                                    {routineMeta.warnings && (
                                                        <p className="text-sm font-medium text-amber-700 dark:text-amber-300 mb-2">
                                                            <span className="font-bold">{t("userRoutines.labels.warnings")}</span> {routineMeta.warnings}
                                                        </p>
                                                    )}
                                                    {routine.objectif && (
                                                        <p className="text-sm font-bold text-foreground">
                                                            <span className="text-primary">{t("userRoutines.labels.goal")}</span> {cleanGoal}
                                                        </p>
                                                    )}
                                                </div>
                                            )}

                                            <AnimatePresence mode="popLayout">
                                                {[...(routine.steps || [])].sort((a, b) => a.ordre - b.ordre).map((step, index) => (
                                                    <motion.div
                                                        key={step.id}
                                                        layout
                                                        initial={{ opacity: 0, x: -20 }}
                                                        animate={{ opacity: 1, x: 0 }}
                                                        transition={{ delay: index * 0.1 }}
                                                        className={`group relative bg-card border transition-all duration-300 rounded-[32px] overflow-hidden ${step.completed
                                                            ? "border-green-500/20 bg-green-500/[0.02] opacity-80"
                                                            : "border-border shadow-sm hover:shadow-xl hover:border-primary/20"
                                                            }`}
                                                    >
                                                        <div className="p-6 md:p-8 flex items-center gap-6">
                                                            <button
                                                                onClick={() => toggleStep(routine.id, step.id)}
                                                                className={`w-14 h-14 rounded-2xl flex items-center justify-center transition-all flex-shrink-0 ${step.completed
                                                                    ? "bg-green-500 text-white shadow-lg shadow-green-500/20"
                                                                    : "bg-muted text-muted-foreground group-hover:bg-primary group-hover:text-white group-hover:shadow-lg group-hover:shadow-primary/20"
                                                                    }`}
                                                            >
                                                                {step.completed ? <CheckCircle2 className="w-8 h-8" /> : <span className="text-xl font-black">{step.ordre}</span>}
                                                            </button>

                                                            <div className="flex-1 min-w-0">
                                                                <div className="flex items-center gap-2 mb-1">
                                                                    <span className="text-[10px] font-black uppercase tracking-widest text-primary/60">
                                                                        {t("userRoutines.labels.step", { step: step.ordre })}
                                                                    </span>
                                                                    {activeTab === 'morning' && !step.completed && <Sun className="w-3 h-3 text-amber-500 opacity-50" />}
                                                                </div>
                                                                <h4 className="text-lg font-black text-foreground">{step.action}</h4>
                                                                {isPremiumUser && (
                                                                    <RoutineItemScraper
                                                                        action={step.action}
                                                                        enabled={isScrapingEnabled && !isModalOpen}
                                                                    />
                                                                )}
                                                                {step.completed && step.completedAt && (
                                                                    <p className="text-xs text-muted-foreground mt-1">
                                                                        {t("userRoutines.labels.completedOn", { date: new Date(step.completedAt).toLocaleDateString() })}
                                                                    </p>
                                                                )}
                                                            </div>

                                                            <div className="flex-shrink-0">
                                                                {!step.completed && (
                                                                    <button
                                                                        onClick={() => toggleStep(routine.id, step.id)}
                                                                        className="p-3 rounded-2xl bg-primary/5 text-primary hover:bg-primary hover:text-white transition-all"
                                                                    >
                                                                        <Play className="w-5 h-5" />
                                                                    </button>
                                                                )}
                                                            </div>
                                                        </div>
                                                    </motion.div>
                                                ))}
                                            </AnimatePresence>
                                        </div>
                                    );
                                })}
                            </div>
                        )}

                        {currentRoutines.length > 0 && (
                            <div className="pt-8">
                                <button
                                    onClick={() => {
                                        currentRoutines.forEach(routine => {
                                            routine.steps?.forEach(step => {
                                                if (step.completed) {
                                                    toggleStep(routine.id, step.id);
                                                }
                                            });
                                        });
                                    }}
                                    className="w-full py-5 bg-primary text-primary-foreground rounded-[24px] font-black uppercase tracking-widest shadow-2xl shadow-primary/30 hover:scale-[1.01] active:scale-[0.99] transition-all flex items-center justify-center gap-3"
                                >
                                    <RotateCcw className="w-5 h-5" /> {t("userRoutines.actions.restartRoutine")}
                                </button>
                            </div>
                        )}
                    </div>

                    <div className="lg:col-span-4 space-y-8">
                        <div className="bg-card border border-border rounded-[40px] p-8 shadow-sm">
                            <div className="flex items-center justify-between mb-8">
                                <h4 className="text-lg font-black text-foreground">{t("userRoutines.labels.consistency")}</h4>
                                <span className="text-primary font-black">
                                    {consistencyLoading ? "…" : `${consistency?.percentage ?? 0}%`}
                                </span>
                            </div>

                            <div className="grid grid-cols-7 gap-1 mb-8">
                                {(consistency?.days || Array.from({ length: 7 }).map(() => ({ day: "", completed: false }))).map((d, i) => {
                                    const label = d.day
                                        ? new Date(`${d.day}T00:00:00Z`).toLocaleDateString("en-US", { weekday: "short" }).slice(0, 1)
                                        : "";
                                    return (
                                        <div key={d.day || i} className="flex flex-col items-center gap-2">
                                            <div
                                                className={`w-9 h-9 md:w-10 md:h-10 rounded-2xl flex items-center justify-center transition-all ${d.completed
                                                    ? "bg-green-500 text-white shadow-lg shadow-green-500/20"
                                                    : "bg-muted text-muted-foreground/40"
                                                    }`}
                                                title={d.day ? `${d.day} — ${d.completed ? "Done" : "Missed"}` : d.completed ? "Done" : "Missed"}
                                            >
                                                {d.completed ? <CheckCircle2 className="w-5 h-5" /> : <Circle className="w-4 h-4 opacity-30" />}
                                            </div>
                                            <span className="text-[10px] font-black uppercase tracking-tighter text-muted-foreground/60">{label}</span>
                                        </div>
                                    );
                                })}
                            </div>

                            <div className="p-5 bg-muted/30 border border-border/50 rounded-3xl flex items-center gap-4 group hover:bg-muted/50 transition-colors">
                                <div className="p-3 bg-slate-900 text-white rounded-2xl shadow-lg group-hover:scale-110 transition-transform">
                                    <Flame className="w-5 h-5" />
                                </div>
                                <p className="text-sm font-bold text-foreground">
                                    {consistencyLoading ? "…" : t("userRoutines.labels.dayStreak", { streak: consistency?.streak ?? 0 })}{" "}
                                    <span className="text-muted-foreground font-medium italic">{t("userRoutines.labels.glowing")}</span>
                                </p>
                            </div>
                        </div>

                        <div className="relative group bg-slate-900 border border-slate-800 rounded-[40px] p-8 text-white overflow-hidden">
                            <div className="absolute top-0 right-0 w-32 h-32 bg-primary/10 rounded-full blur-3xl -mr-16 -mt-16" />
                            <div className="relative z-10">
                                <div className="flex items-center gap-3 mb-4">
                                    <div className="p-2 bg-white/10 rounded-xl">
                                        <Droplets className="w-5 h-5 text-primary" />
                                    </div>
                                    <h4 className="text-lg font-black tracking-tight">{t("userRoutines.labels.dailyInsight")}</h4>
                                </div>
                                <p className="text-sm font-medium text-slate-300 leading-relaxed mb-6">
                                    {(() => {
                                        // Dynamic insight based on the first found skin type in auto-routines
                                        const skinType = currentRoutines.map(r => parseRoutineMeta(r.envie).skinType).find(Boolean);
                                        const insightMap: Record<string, string> = {
                                            'oily': "Use lightweight, non-comedogenic serums to manage sebum without clogging pores.",
                                            'dry': "Layer a hydrating toner under your moisturizer to deeply replenish dry skin cells.",
                                            'sensitive': "Introduce new active products slowly and one at a time to avoid irritation flares.",
                                            'combination': "Focus hydration on cheeks and use balancing cleansers for your T-zone.",
                                            'normal': "Maintaing a consistent barrier with ceramides will keep your glow through the seasons."
                                        };

                                        const key = Object.keys(insightMap).find(k => skinType?.toLowerCase().includes(k));
                                        return insightMap[key || ''] || "Always apply your SPF, even on cloudy days. UV rays can penetrate through clouds and windows to affect your skin.";
                                    })()}
                                </p>
                                <button className="flex items-center gap-2 text-primary font-black text-xs uppercase tracking-widest group-hover:translate-x-1 transition-transform">
                                    Read deep dive <ArrowRight className="w-4 h-4" />
                                </button>
                            </div>
                        </div>

                        {(() => {
                            // Logic to find a dynamic alert based on actual routine steps
                            const allSteps = currentRoutines.flatMap(r => r.steps || []);
                            const sensitiveKeywords = ['Serum', 'Vitamin C', 'Retinol', 'Acid', 'Treatment', 'Active'];

                            // Find steps that might be sensitive products
                            const sensitiveStep = allSteps.find(s =>
                                sensitiveKeywords.some(keyword => s.action.toLowerCase().includes(keyword.toLowerCase()))
                            );

                            const productName = sensitiveStep
                                ? sensitiveStep.action.split(':')[0].trim()
                                : "Vitamin C Serum";

                            // Mock expiration date based on the product
                            const daysLeft = sensitiveStep ? (sensitiveStep.id % 20) + 5 : 12;

                            // Component-based explanation logic
                            const getExplanation = (name: string) => {
                                const n = name.toLowerCase();
                                if (n.includes('vitamin c')) return "Unstable active — can oxidize if exposed to light.";
                                if (n.includes('retinol')) return "UV sensitive — keep in a dark place to stay potent.";
                                if (n.includes('acid')) return "Potent exfoliant — best used before the seal weakens.";
                                if (n.includes('serum')) return "High concentration — use quickly for best results.";
                                return "Active formula — monitor for any changes in color or smell.";
                            };

                            const explanation = getExplanation(productName);

                            return (
                                <div className="bg-amber-500/5 border border-amber-500/10 rounded-[40px] p-8">
                                    <div className="flex items-center justify-between mb-6">
                                        <h4 className="text-sm font-black text-amber-700 dark:text-amber-400 uppercase tracking-widest flex items-center gap-2">
                                            <AlertTriangle className="w-4 h-4" /> Shelf Life Alert
                                        </h4>
                                    </div>

                                    <div className="flex items-center gap-4 bg-white/50 dark:bg-black/20 p-4 rounded-[24px]">
                                        <div className="w-12 h-12 bg-amber-500/10 rounded-2xl flex items-center justify-center text-amber-600">
                                            <Clock className="w-6 h-6" />
                                        </div>
                                        <div>
                                            <h5 className="text-sm font-black text-foreground leading-tight">{productName}</h5>
                                            <p className="text-[10px] font-bold text-amber-600 dark:text-amber-400 uppercase tracking-widest mt-0.5">Expires in {daysLeft} days</p>
                                        </div>
                                    </div>
                                    <p className="mt-4 text-[10px] font-medium text-amber-800/60 dark:text-amber-400/40 italic leading-relaxed">
                                        Note: {explanation}
                                    </p>
                                </div>
                            );
                        })()}
                    </div>
                </div>

                <footer className="mt-20 text-center pb-10 space-y-4">
                    <p className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground/30">
                        © 2025 Lumina Skincare Routine Tracker • Formulated with DeepSkyn AI
                    </p>
                </footer>

                {userId && (
                    <AddRoutineModal
                        isOpen={isModalOpen}
                        onClose={handleCloseRoutineModal}
                        userId={userId}
                        routineToEdit={routineToEdit}
                    />
                )}

                <DeleteRoutineModal
                    isOpen={isDeleteModalOpen}
                    onClose={() => setIsDeleteModalOpen(false)}
                    onConfirm={confirmDeleteRoutine}
                    routineName={routineToDelete?.objectif || routineToDelete?.envie || t("userRoutines.labels.routine")}
                    loading={deleteLoading}
                />

                <SequentialWarningModal
                    isOpen={isWarningModalOpen}
                    onClose={() => setIsWarningModalOpen(false)}
                    message={warningModalMessage}
                />
            </div>
        </UserLayout>
    );
}
