"use client";

import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useSession } from "next-auth/react";
import {
    Sun,
    Moon,
    Calendar,
    CheckCircle2,
    Circle,
    AlertTriangle,
    Flame,
    Clock,
    Play,
    RotateCcw,
    ArrowRight,
    Droplets,
    Plus,
    Trash2,
    ChevronRight,
} from "lucide-react";

import { UserLayout } from "@/app/ui/UserLayout";
import { toast } from "sonner";
import { useAppDispatch, useAppSelector } from "@/store/hooks";
import { deleteRoutine, fetchUserRoutines, markStepCompleted, toggleStepCompletedLocally } from "@/store/slices/routineSlice";
import { AddRoutineModal } from "@/app/components/user/AddRoutineModal";
import { DeleteRoutineModal } from "@/app/components/user/DeleteRoutineModal";

// --- Types ---
type RoutineType = "morning" | "night" | "weekly";

type ConsistencyResponse = {
    type: RoutineType;
    percentage: number;
    streak: number;
    days: Array<{ day: string; completed: boolean }>;
};

type ParsedRoutineMeta = {
    isAutoGenerated: boolean;
    idempotencyKey?: string;
    source?: string;
    skinType?: string;
    score?: string;
    durationWeeks?: string;
    warnings?: string;
    motivationText?: string;
};

const parseRoutineMeta = (envie?: string): ParsedRoutineMeta => {
    const raw = String(envie || "").trim();
    if (!raw.startsWith("AUTO_ROUTINE:")) {
        return {
            isAutoGenerated: false,
            motivationText: raw,
        };
    }

    const parts = raw.split(" | ").map((p) => p.trim()).filter(Boolean);
    const meta: ParsedRoutineMeta = {
        isAutoGenerated: true,
    };

    for (let i = 0; i < parts.length; i += 1) {
        const token = parts[i];
        if (i === 0 && token.startsWith("AUTO_ROUTINE:")) {
            meta.idempotencyKey = token.replace("AUTO_ROUTINE:", "").trim();
            continue;
        }

        if (token.startsWith("source=")) {
            meta.source = token.replace("source=", "").trim();
            continue;
        }

        if (token.startsWith("skinType=")) {
            meta.skinType = token.replace("skinType=", "").trim();
            continue;
        }

        if (token.startsWith("score=")) {
            meta.score = token.replace("score=", "").trim();
            continue;
        }

        if (token.startsWith("durationWeeks=")) {
            meta.durationWeeks = token.replace("durationWeeks=", "").trim();
            continue;
        }

        if (token.startsWith("warnings=")) {
            const warningHead = token.replace("warnings=", "").trim();
            const warningTail = parts.slice(i + 1).join(" | ").trim();
            meta.warnings = warningTail ? `${warningHead} | ${warningTail}` : warningHead;
            break;
        }
    }

    meta.motivationText = "Routine generated automatically from your latest quiz analysis.";
    return meta;
};

const cleanAutoGoalLabel = (objectif?: string, isAutoGenerated?: boolean) => {
    const raw = String(objectif || "").trim();
    if (!raw) return "Routine";
    if (!isAutoGenerated) return raw;
    return raw
        .replace(/\s-\sMorning$/i, "")
        .replace(/\s-\sEvening$/i, "")
        .replace(/\s-\sWeekly Plan$/i, "")
        .trim();
};

// --- Components ---

const ProgressBar = ({ current, total, type }: { current: number; total: number; type: string }) => {
    const percentage = total > 0 ? (current / total) * 100 : 0;
    return (
        <div className="relative flex items-center justify-center p-6 bg-card dark:bg-card/40 border border-border/50 rounded-3xl shadow-xl shadow-primary/5">
            <div className="relative w-24 h-24">
                <svg className="w-full h-full -rotate-90">
                    <circle
                        cx="48"
                        cy="48"
                        r="40"
                        stroke="currentColor"
                        strokeWidth="8"
                        fill="transparent"
                        className="text-muted/20"
                    />
                    <motion.circle
                        cx="48"
                        cy="48"
                        r="40"
                        stroke="currentColor"
                        strokeWidth="8"
                        fill="transparent"
                        strokeDasharray="251.2"
                        initial={{ strokeDashoffset: 251.2 }}
                        animate={{ strokeDashoffset: 251.2 - (251.2 * percentage) / 100 }}
                        transition={{ duration: 1, ease: "easeOut" }}
                        strokeLinecap="round"
                        className="text-primary"
                    />
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                    <span className="text-xl font-black text-foreground">{current}/{total}</span>
                </div>
            </div>
            <div className="ml-6 flex-1">
                <h4 className="text-sm font-black text-muted-foreground uppercase tracking-widest mb-1">
                    Routine {type}
                </h4>
                <p className="text-lg font-bold text-foreground leading-tight">
                    {percentage === 100 ? "Sparkle time! ✨" : percentage > 50 ? "Halfway there!" : "Keep going!"}
                </p>
            </div>
        </div>
    );
};

export default function RoutinePage() {
    const { data: session } = useSession();
    const dispatch = useAppDispatch();
    const { routines, loading } = useAppSelector((state) => state.routine);
    const [activeTab, setActiveTab] = useState<RoutineType>("morning");
    const [userName, setUserName] = useState("");
    const [userId, setUserId] = useState<number | null>(null);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [routineToEdit, setRoutineToEdit] = useState<any>(null);
    const [isDeleteModalOpen, setIsDeleteModalOpen] = useState(false);
    const [routineToDelete, setRoutineToDelete] = useState<any>(null);
    const [deleteLoading, setDeleteLoading] = useState(false);
    const [consistency, setConsistency] = useState<ConsistencyResponse | null>(null);
    const [consistencyLoading, setConsistencyLoading] = useState(false);

    // Fetch user and routines
    useEffect(() => {
        const fetchUserData = async () => {
            if (session?.user?.email) {
                try {
                    const response = await fetch('/api/user/profile');
                    if (response.ok) {
                        const userData = await response.json();
                        setUserName(userData.nom || "User");
                        setUserId(userData.id);

                        // Fetch routines
                        if (userData.id) {
                            dispatch(fetchUserRoutines(userData.id));
                        }
                    }
                } catch (error) {
                    console.error('Error fetching user data:', error);
                }
            }
        };
        fetchUserData();
    }, [session, dispatch]);

    // Fetch consistency for current tab
    useEffect(() => {
        let cancelled = false;
        const run = async () => {
            try {
                setConsistencyLoading(true);
                const res = await fetch(`/api/user/routines/consistency?type=${activeTab}`);
                if (!res.ok) throw new Error("Failed to load consistency");
                const data = (await res.json()) as ConsistencyResponse;
                if (!cancelled) setConsistency(data);
            } catch {
                if (!cancelled) setConsistency(null);
            } finally {
                if (!cancelled) setConsistencyLoading(false);
            }
        };
        run();
        return () => {
            cancelled = true;
        };
    }, [activeTab]);

    // Filter routines by active tab
    const currentRoutines = routines.filter(r => r.type === activeTab);
    const currentSteps = currentRoutines.flatMap((r) => r.steps || []);
    const completedCount = currentSteps.filter(s => s.completed).length;

    const toggleStep = async (routineId: number, stepId: number) => {
        const routine = currentRoutines.find((r) => r.id === routineId);
        const step = routine?.steps?.find((s) => s.id === stepId);
        const newCompleted = !step?.completed;

        dispatch(toggleStepCompletedLocally({ routineId, stepId }));

        try {
            await dispatch(markStepCompleted({
                routineId,
                stepId,
                completed: newCompleted
            })).unwrap();

            if (userId) dispatch(fetchUserRoutines(userId));

            if (newCompleted) {
                const stepData = routine?.steps?.find((s) => s.id === stepId);
                toast.success(`${stepData?.action} completed! ✨`, {
                    description: "Your skin thanks you.",
                    position: "bottom-right",
                });
            }
        } catch {
            dispatch(toggleStepCompletedLocally({ routineId, stepId }));
            toast.error("Failed to update.");
        }
    };

    const handleNewRoutine = () => {
        setRoutineToEdit(null);
        setIsModalOpen(true);
    };

    const handleEditRoutine = (routine: any) => {
        setRoutineToEdit(routine);
        setIsModalOpen(true);
    };

    const handleDeleteRoutine = (routine: any) => {
        setRoutineToDelete(routine);
        setIsDeleteModalOpen(true);
    };

    const confirmDeleteRoutine = async () => {
        if (!routineToDelete) return;
        setDeleteLoading(true);
        try {
            await dispatch(deleteRoutine(routineToDelete.id)).unwrap();
            toast.success("Routine deleted ✨", { position: "bottom-right" });
            setIsDeleteModalOpen(false);
        } catch {
            toast.error("Failed to delete routine", { position: "bottom-right" });
        } finally {
            setDeleteLoading(false);
        }
    };

    return (
        <UserLayout userName={userName} userPhoto="/avatar.png">
            <div className="min-h-full py-6 px-4 md:px-8 max-w-[1200px] mx-auto relative space-y-6">

                {/* Breadcrumb */}
                <nav className="flex items-center gap-2 text-sm text-muted-foreground/60">
                    <span>User</span>
                    <ChevronRight size={14} />
                    <span className="text-foreground font-medium">Routines</span>
                </nav>


                {/* Header Section */}
                <header className="mb-12 flex flex-col md:flex-row md:items-end justify-between gap-8">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="space-y-3"
                    >
                        <h1 className="text-4xl md:text-5xl font-black tracking-tight text-foreground">
                            Hello, {userName}
                        </h1>
                        <div className="flex flex-wrap gap-2 pt-1">
                            {["Dry", "Sensitive", "Eco-Conscious"].map(tag => (
                                <span key={tag} className="px-3 py-1 bg-primary/5 text-primary border border-primary/10 rounded-full text-[10px] font-black uppercase tracking-wider">
                                    {tag}
                                </span>
                            ))}
                        </div>
                    </motion.div>

                    <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="w-full md:w-auto min-w-[300px]"
                    >
                        <ProgressBar current={completedCount} total={currentSteps.length} type={activeTab} />
                    </motion.div>
                </header>

                {/* Tab Switcher */}
                <div className="flex flex-wrap items-center gap-4 mb-10">
                    <div className="flex p-1.5 bg-muted/30 backdrop-blur-md rounded-[24px] border border-border/50">
                        {[
                            { id: "morning", label: "Morning", icon: Sun },
                            { id: "night", label: "Night", icon: Moon },
                            { id: "weekly", label: "Weekly", icon: Calendar },
                        ].map((tab) => (
                            <button
                                key={tab.id}
                                onClick={() => setActiveTab(tab.id as RoutineType)}
                                className={`flex items-center gap-2.5 px-6 py-3 rounded-full text-xs font-black uppercase tracking-widest transition-all duration-300 ${activeTab === tab.id
                                    ? "bg-card text-foreground shadow-lg shadow-black/5 border border-border/10"
                                    : "text-muted-foreground hover:text-foreground"
                                    }`}
                            >
                                <tab.icon className={`w-4 h-4 ${activeTab === tab.id ? "text-primary" : ""}`} />
                                {tab.label}
                            </button>
                        ))}
                    </div>

                    <button
                        onClick={handleNewRoutine}
                        className="flex items-center gap-2 px-6 py-3 bg-primary text-primary-foreground rounded-full text-xs font-black uppercase tracking-widest hover:scale-105 active:scale-95 transition-all shadow-lg shadow-primary/20"
                    >
                        <Plus className="w-4 h-4" />
                        New Routine
                    </button>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-start">
                    <div className="lg:col-span-8 space-y-6">
                        <h3 className="text-xl font-black text-foreground mb-6 flex items-center gap-3 uppercase tracking-tighter">
                            Routine {activeTab}
                            <span className="h-px flex-1 bg-border/50" />
                        </h3>

                        {loading ? (
                            <div className="flex items-center justify-center py-20">
                                <div className="animate-spin rounded-full h-12 w-12 border-4 border-primary border-t-transparent"></div>
                            </div>
                        ) : currentRoutines.length === 0 ? (
                            <div className="text-center py-20">
                                <div className="inline-flex p-6 bg-muted/30 rounded-full mb-6">
                                    <Calendar className="w-12 h-12 text-muted-foreground" />
                                </div>
                                <h3 className="text-xl font-black text-foreground mb-2">
                                    No {activeTab} routines
                                </h3>
                                <p className="text-muted-foreground mb-8">
                                    Create your first personalized routine
                                </p>
                                <button
                                    onClick={handleNewRoutine}
                                    className="inline-flex items-center gap-2 px-8 py-4 bg-primary text-primary-foreground rounded-full font-black uppercase tracking-widest hover:scale-105 transition-all shadow-lg shadow-primary/20"
                                >
                                    <Plus className="w-5 h-5" />
                                    Create Routine
                                </button>
                            </div>
                        ) : (
                            <div className="space-y-4">
                                {currentRoutines.map((routine) => {
                                    const routineMeta = parseRoutineMeta(routine.envie);
                                    const cleanGoal = cleanAutoGoalLabel(routine.objectif, routineMeta.isAutoGenerated);

                                    return (
                                    <div key={routine.id} className="space-y-4">
                                        <div className="flex items-center justify-between gap-4">
                                            <div className="min-w-0">
                                                <p className="text-xs font-black uppercase tracking-widest text-muted-foreground/60">
                                                    {routineMeta.isAutoGenerated ? "AI Routine" : "Routine"}
                                                </p>
                                                <h4 className="text-lg font-black text-foreground truncate">
                                                    {cleanGoal || routine.envie || "Routine"}
                                                </h4>
                                            </div>
                                            <div className="flex items-center gap-2">
                                                <button
                                                    type="button"
                                                    onClick={() => handleEditRoutine(routine)}
                                                    className="flex items-center gap-2 px-4 py-2 rounded-2xl bg-primary/10 border border-primary/20 text-xs font-black uppercase tracking-widest text-primary hover:bg-primary/20 transition-colors"
                                                >
                                                    Edit
                                                </button>
                                                <button
                                                    type="button"
                                                    onClick={() => handleDeleteRoutine(routine)}
                                                    className="flex items-center gap-2 px-4 py-2 rounded-2xl bg-muted/30 border border-border/50 text-xs font-black uppercase tracking-widest text-muted-foreground hover:text-foreground hover:bg-muted/50 transition-colors"
                                                >
                                                    <Trash2 className="w-4 h-4" />
                                                    Delete
                                                </button>
                                            </div>
                                        </div>

                                        {(routineMeta.skinType || routineMeta.score || routineMeta.durationWeeks) && (
                                            <div className="flex flex-wrap gap-2">
                                                {routineMeta.skinType && (
                                                    <span className="px-3 py-1 rounded-full bg-primary/10 text-primary text-[10px] font-black uppercase tracking-widest border border-primary/20">
                                                        Skin: {routineMeta.skinType}
                                                    </span>
                                                )}
                                                {routineMeta.score && (
                                                    <span className="px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 text-[10px] font-black uppercase tracking-widest border border-emerald-500/20">
                                                        Score: {routineMeta.score}/100
                                                    </span>
                                                )}
                                                {routineMeta.durationWeeks && (
                                                    <span className="px-3 py-1 rounded-full bg-sky-500/10 text-sky-700 dark:text-sky-300 text-[10px] font-black uppercase tracking-widest border border-sky-500/20">
                                                        Duration: {routineMeta.durationWeeks} weeks
                                                    </span>
                                                )}
                                            </div>
                                        )}

                                        {(routine.objectif || routine.envie) && (
                                            <div className="bg-primary/5 border border-primary/10 rounded-3xl p-6 mb-6">
                                                {routineMeta.motivationText && (
                                                    <p className="text-sm font-bold text-foreground mb-2">
                                                        <span className="text-primary">Motivation:</span> {routineMeta.motivationText}
                                                    </p>
                                                )}
                                                {routineMeta.warnings && (
                                                    <p className="text-sm font-medium text-amber-700 dark:text-amber-300 mb-2">
                                                        <span className="font-bold">Warnings:</span> {routineMeta.warnings}
                                                    </p>
                                                )}
                                                {routine.objectif && (
                                                    <p className="text-sm font-bold text-foreground">
                                                        <span className="text-primary">Goal:</span> {cleanGoal}
                                                    </p>
                                                )}
                                            </div>
                                        )}

                                        <AnimatePresence mode="popLayout">
                                            {[...(routine.steps || [])].sort((a, b) => a.ordre - b.ordre).map((step, index) => (
                                                <motion.div
                                                    key={step.id}
                                                    layout
                                                    initial={{ opacity: 0, x: -20 }}
                                                    animate={{ opacity: 1, x: 0 }}
                                                    transition={{ delay: index * 0.1 }}
                                                    className={`group relative bg-card border transition-all duration-300 rounded-[32px] overflow-hidden ${step.completed
                                                        ? "border-green-500/20 bg-green-500/[0.02] opacity-80"
                                                        : "border-border shadow-sm hover:shadow-xl hover:border-primary/20"
                                                        }`}
                                                >
                                                    <div className="p-6 md:p-8 flex items-center gap-6">
                                                        <button
                                                            onClick={() => toggleStep(routine.id, step.id)}
                                                            className={`w-14 h-14 rounded-2xl flex items-center justify-center transition-all flex-shrink-0 ${step.completed
                                                                ? "bg-green-500 text-white shadow-lg shadow-green-500/20"
                                                                : "bg-muted text-muted-foreground group-hover:bg-primary group-hover:text-white group-hover:shadow-lg group-hover:shadow-primary/20"
                                                                }`}
                                                        >
                                                            {step.completed ? <CheckCircle2 className="w-8 h-8" /> : <span className="text-xl font-black">{step.ordre}</span>}
                                                        </button>

                                                        <div className="flex-1 min-w-0">
                                                            <div className="flex items-center gap-2 mb-1">
                                                                <span className="text-[10px] font-black uppercase tracking-widest text-primary/60">
                                                                    Step {step.ordre}
                                                                </span>
                                                                {activeTab === 'morning' && !step.completed && <Sun className="w-3 h-3 text-amber-500 opacity-50" />}
                                                            </div>
                                                            <h4 className="text-lg font-black text-foreground">{step.action}</h4>
                                                            {step.completed && step.completedAt && (
                                                                <p className="text-xs text-muted-foreground mt-1">
                                                                    ✓ Completed on {new Date(step.completedAt).toLocaleDateString()}
                                                                </p>
                                                            )}
                                                        </div>

                                                        <div className="flex-shrink-0">
                                                            {!step.completed && (
                                                                <button
                                                                    onClick={() => toggleStep(routine.id, step.id)}
                                                                    className="p-3 rounded-2xl bg-primary/5 text-primary hover:bg-primary hover:text-white transition-all"
                                                                >
                                                                    <Play className="w-5 h-5" />
                                                                </button>
                                                            )}
                                                        </div>
                                                    </div>
                                                </motion.div>
                                            ))}
                                        </AnimatePresence>
                                    </div>
                                );})}
                            </div>
                        )}

                        {currentRoutines.length > 0 && (
                            <div className="pt-8">
                                <button
                                    onClick={() => {
                                        currentRoutines.forEach(routine => {
                                            routine.steps?.forEach(step => {
                                                if (step.completed) {
                                                    toggleStep(routine.id, step.id);
                                                }
                                            });
                                        });
                                    }}
                                    className="w-full py-5 bg-primary text-primary-foreground rounded-[24px] font-black uppercase tracking-widest shadow-2xl shadow-primary/30 hover:scale-[1.01] active:scale-[0.99] transition-all flex items-center justify-center gap-3"
                                >
                                    <RotateCcw className="w-5 h-5" /> Restart Routine
                                </button>
                            </div>
                        )}
                    </div>

                    <div className="lg:col-span-4 space-y-8">
                        <div className="bg-card border border-border rounded-[40px] p-8 shadow-sm">
                            <div className="flex items-center justify-between mb-8">
                                <h4 className="text-lg font-black text-foreground">Consistency</h4>
                                <span className="text-primary font-black">
                                    {consistencyLoading ? "…" : `${consistency?.percentage ?? 0}%`}
                                </span>
                            </div>

                            <div className="grid grid-cols-7 gap-1 mb-8">
                                {(consistency?.days || Array.from({ length: 7 }).map(() => ({ day: "", completed: false }))).map((d, i) => {
                                    const label = d.day
                                        ? new Date(`${d.day}T00:00:00Z`).toLocaleDateString("en-US", { weekday: "short" }).slice(0, 1)
                                        : "";
                                    return (
                                        <div key={d.day || i} className="flex flex-col items-center gap-2">
                                            <div
                                                className={`w-9 h-9 md:w-10 md:h-10 rounded-2xl flex items-center justify-center transition-all ${d.completed
                                                    ? "bg-green-500 text-white shadow-lg shadow-green-500/20"
                                                    : "bg-muted text-muted-foreground/40"
                                                    }`}
                                                title={d.day ? `${d.day} — ${d.completed ? "Done" : "Missed"}` : d.completed ? "Done" : "Missed"}
                                            >
                                                {d.completed ? <CheckCircle2 className="w-5 h-5" /> : <Circle className="w-4 h-4 opacity-30" />}
                                            </div>
                                            <span className="text-[10px] font-black uppercase tracking-tighter text-muted-foreground/60">{label}</span>
                                        </div>
                                    );
                                })}
                            </div>

                            <div className="p-5 bg-muted/30 border border-border/50 rounded-3xl flex items-center gap-4 group hover:bg-muted/50 transition-colors">
                                <div className="p-3 bg-slate-900 text-white rounded-2xl shadow-lg group-hover:scale-110 transition-transform">
                                    <Flame className="w-5 h-5" />
                                </div>
                                <p className="text-sm font-bold text-foreground">
                                    {consistencyLoading ? "…" : `${consistency?.streak ?? 0}`}-Day Streak!{" "}
                                    <span className="text-muted-foreground font-medium italic">You&apos;re glowing.</span>
                                </p>
                            </div>
                        </div>

                        <div className="relative group bg-slate-900 border border-slate-800 rounded-[40px] p-8 text-white overflow-hidden">
                            <div className="absolute top-0 right-0 w-32 h-32 bg-primary/10 rounded-full blur-3xl -mr-16 -mt-16" />
                            <div className="relative z-10">
                                <div className="flex items-center gap-3 mb-4">
                                    <div className="p-2 bg-white/10 rounded-xl">
                                        <Droplets className="w-5 h-5 text-primary" />
                                    </div>
                                    <h4 className="text-lg font-black tracking-tight">Daily Insight</h4>
                                </div>
                                <p className="text-sm font-medium text-slate-300 leading-relaxed mb-6">
                                    Always apply your SPF, even on cloudy days. UV rays can penetrate through clouds and windows, causing premature aging and sensitive skin flare-ups.
                                </p>
                                <button className="flex items-center gap-2 text-primary font-black text-xs uppercase tracking-widest group-hover:translate-x-1 transition-transform">
                                    Read deep dive <ArrowRight className="w-4 h-4" />
                                </button>
                            </div>
                        </div>

                        <div className="bg-amber-500/5 border border-amber-500/10 rounded-[40px] p-8">
                            <div className="flex items-center justify-between mb-6">
                                <h4 className="text-sm font-black text-amber-700 dark:text-amber-400 uppercase tracking-widest flex items-center gap-2">
                                    <AlertTriangle className="w-4 h-4" /> Shelf Life Alert
                                </h4>
                            </div>

                            <div className="flex items-center gap-4 bg-white/50 dark:bg-black/20 p-4 rounded-[24px]">
                                <div className="w-12 h-12 bg-amber-500/10 rounded-2xl flex items-center justify-center text-amber-600">
                                    <Clock className="w-6 h-6" />
                                </div>
                                <div>
                                    <h5 className="text-sm font-black text-foreground leading-tight">Vitamin C Serum</h5>
                                    <p className="text-[10px] font-bold text-amber-600 dark:text-amber-400 uppercase tracking-widest mt-0.5">Expires in 12 days</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <footer className="mt-20 text-center pb-10 space-y-4">
                    <p className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground/30">
                        © 2025 Lumina Skincare Routine Tracker • Formulated with DeepSkyn AI
                    </p>
                </footer>

                {userId && (
                    <AddRoutineModal
                        isOpen={isModalOpen}
                        onClose={() => setIsModalOpen(false)}
                        userId={userId}
                        routineToEdit={routineToEdit}
                    />
                )}

                <DeleteRoutineModal
                    isOpen={isDeleteModalOpen}
                    onClose={() => setIsDeleteModalOpen(false)}
                    onConfirm={confirmDeleteRoutine}
                    routineName={routineToDelete?.objectif || routineToDelete?.envie || "Routine"}
                    loading={deleteLoading}
                />
            </div>
        </UserLayout>
    );
}
